#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lichess4545SlackNotifier.Resource", IsApplication=true)]

namespace Lichess4545SlackNotifier
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int common_google_signin_btn_text_dark = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int common_google_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_google_signin_btn_text_dark_disabled = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int common_google_signin_btn_text_dark_focused = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_signin_btn_text_dark_pressed = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_light = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int common_google_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_signin_btn_text_light_disabled = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_signin_btn_text_light_focused = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_signin_btn_text_light_pressed = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_signin_btn_tint = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_horizontal_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int activity_vertical_margin = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int slack_icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int slack_icon_full = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090015
			public const int ActionRefresh = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int ActionSubscriptions = 2131296278;
			
			// aapt resource value: 0x7f090010
			public const int IntervalSpinner = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public const int LoginButton = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int LogoutButton = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int PollContainer = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int activity_main = 2131296265;
			
			// aapt resource value: 0x7f090013
			public const int activity_slack_login = 2131296275;
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int auto = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int dark = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int icon_only = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int light = 2131296264;
			
			// aapt resource value: 0x7f09000b
			public const int linearLayout1 = 2131296267;
			
			// aapt resource value: 0x7f090012
			public const int listView1 = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int login_webview = 2131296276;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090011
			public const int progressBar1 = 2131296273;
			
			// aapt resource value: 0x7f090004
			public const int standard = 2131296260;
			
			// aapt resource value: 0x7f09000a
			public const int status = 2131296266;
			
			// aapt resource value: 0x7f09000f
			public const int textView = 2131296271;
			
			// aapt resource value: 0x7f090005
			public const int wide = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SlackLogin = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu1 = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050019
			public const int ApplicationName = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int Hello = 2131034136;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_enable_button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unknown_issue = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_unsupported_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_wear_update_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_open_on_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_signin_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text_long = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int default_web_client_id = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int firebase_database_url = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int gcm_defaultSenderId = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int google_api_key = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int google_app_id = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int google_crash_reporting_api_key = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int google_storage_bucket = 2131034135;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
